/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank.tech.test.java;

import java.time.LocalDate;
import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        BankAccount bankAccount = new BankAccount();
        bankAccount.deposit(1000, LocalDate.of(2023, 1, 10));
        bankAccount.deposit(2000, LocalDate.of(2023, 1, 13));
        bankAccount.withdraw(500, LocalDate.of(2023, 1, 14));
        System.out.println(bankAccount.generateStatement());
    }
}
